package server.zone.objects.tangible.components.droid;

include engine.core.ManagedObject;
import engine.util.Observer;
import engine.util.Observable;
import server.zone.objects.tangible.components.droid.DroidAutoLootModuleDataComponent;

class DroidAutoLootObserver extends Observer {
	@weakReference
	protected DroidAutoLootModuleDataComponent module;

	public DroidAutoLootObserver(DroidAutoLootModuleDataComponent m) {
		module = m;
	}

	@dirty
	public native int notifyObserverEvent(unsigned int eventType, Observable observable, ManagedObject arg1, long arg2);
}
